/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.Csiswa;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Book;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Client
 */
public class inputSiswa extends javax.swing.JDialog {
    Csiswa cs = new Csiswa();
File file;
 JFileChooser jfc;

    /**
     * Creates new form inputSiswa
     */
    public inputSiswa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
     //   setTanggalDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupJekel = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        tema1 = new Background.tema();
        clPanelTransparan1 = new model.ClPanelTransparan();
        jLabelGambar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtSaudara = new javax.swing.JTextField();
        lblJenisKelamin = new javax.swing.JLabel();
        tglsiwa = new com.toedter.calendar.JDateChooser();
        txtAsal_Sekolah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTempat = new javax.swing.JTextField();
        lblKewarganegaraan = new javax.swing.JLabel();
        txtNomor_Ijazah = new javax.swing.JTextField();
        lblNamaSiswa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        cbAgama = new javax.swing.JComboBox<>();
        lblALamat = new javax.swing.JLabel();
        rbCewe = new javax.swing.JRadioButton();
        grupJekel.add(rbCewe);
        txtNISN = new javax.swing.JTextField();
        cbKWn = new javax.swing.JComboBox<>();
        txt_anak_Ke = new javax.swing.JTextField();
        lblAgama = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTTL = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        grupJekel.add(rbLaki);
        txtNIS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cb_Tahun_Angkatan = new javax.swing.JComboBox<>();
        lblNamaSiswa1 = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        jLabelNamaFileBuku = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tema2 = new Background.tema();
        clPanelTransparan2 = new model.ClPanelTransparan();
        lblNamaAyah1 = new usu.widget.Label();
        lblTempat1 = new usu.widget.Label();
        lblTanggal1 = new usu.widget.Label();
        lblAgamaAyah1 = new usu.widget.Label();
        lblPendidikanAyah1 = new usu.widget.Label();
        lblPekerjaan1 = new usu.widget.Label();
        lblPenghasilanAyah1 = new usu.widget.Label();
        cbpenghasilanAyah1 = new javax.swing.JComboBox<>();
        txtpekerjaanAyah1 = new usu.widget.TextBox();
        cbAgamaAYah1 = new javax.swing.JComboBox<>();
        tglAyah1 = new com.toedter.calendar.JDateChooser();
        txttmpatAyah1 = new usu.widget.TextBox();
        txtNAmaAyah1 = new usu.widget.TextBox();
        cbPendidikanAyah = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        clPanelTransparan3 = new model.ClPanelTransparan();
        txtNamaIbu1 = new usu.widget.TextBox();
        cbPenghasilanIbu1 = new javax.swing.JComboBox<>();
        label17 = new usu.widget.Label();
        label24 = new usu.widget.Label();
        label26 = new usu.widget.Label();
        label25 = new usu.widget.Label();
        label18 = new usu.widget.Label();
        tglIbu1 = new com.toedter.calendar.JDateChooser();
        txtPekerjaanIbu1 = new usu.widget.TextBox();
        CbAgamaIbu1 = new javax.swing.JComboBox<>();
        cbPendidikanIbu = new javax.swing.JComboBox<>();
        label20 = new usu.widget.Label();
        txtTempatIbu1 = new usu.widget.TextBox();
        label19 = new usu.widget.Label();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelGambar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelGambar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout clPanelTransparan1Layout = new javax.swing.GroupLayout(clPanelTransparan1);
        clPanelTransparan1.setLayout(clPanelTransparan1Layout);
        clPanelTransparan1Layout.setHorizontalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        clPanelTransparan1Layout.setVerticalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel6.setText("Anak Ke");

        lblJenisKelamin.setText("Jenis Kelamin");

        tglsiwa.setDateFormatString("dd MMMMM yyyy");

        jLabel3.setText("Asal Sekolah");

        lblKewarganegaraan.setText("Kewarganegaraan");

        lblNamaSiswa.setText("Nama Lengkap");

        jLabel1.setText("NIS / NISN");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jLabel8.setText("Bersaduara");

        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Islam", "Kristen Katholik", "Kristen Protestan", "Hindu", "Budha", "Konghucu", "Kepercayaan" }));

        lblALamat.setText("Alamat");

        rbCewe.setText("Perempuan");

        cbKWn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Asing", "Indonesia", "-" }));

        txt_anak_Ke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anak_KeActionPerformed(evt);
            }
        });

        lblAgama.setText("Agama");

        jLabel7.setText("Dari ");

        jLabel4.setText("Nomor Ijazah");

        lblTTL.setText("Tempat Tgl Lahir");

        rbLaki.setText("Laki - laki");

        txtNIS.setBackground(new java.awt.Color(255, 255, 204));
        txtNIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNISKeyTyped(evt);
            }
        });

        jLabel11.setText("Tahun Angkatan");

        cb_Tahun_Angkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016/2017", "2017/2018", "2018/2019", "2019/2020", "2020/2021" }));

        lblNamaSiswa1.setText("No. Hp");

        jLabelNamaFileBuku.setText("Gambar ");

        jButton1.setText("Pilih Gambar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tema1Layout = new javax.swing.GroupLayout(tema1);
        tema1.setLayout(tema1Layout);
        tema1Layout.setHorizontalGroup(
            tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tema1Layout.createSequentialGroup()
                            .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(lblNamaSiswa)
                                .addComponent(lblJenisKelamin)
                                .addComponent(lblTTL)
                                .addComponent(lblAgama))
                            .addGap(41, 41, 41))
                        .addGroup(tema1Layout.createSequentialGroup()
                            .addComponent(lblKewarganegaraan)
                            .addGap(32, 32, 32)))
                    .addGroup(tema1Layout.createSequentialGroup()
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(lblALamat)
                            .addComponent(lblNamaSiswa1))
                        .addGap(41, 41, 41)))
                .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tema1Layout.createSequentialGroup()
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Tahun_Angkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(242, 242, 242))
                    .addGroup(tema1Layout.createSequentialGroup()
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tema1Layout.createSequentialGroup()
                                .addComponent(txt_anak_Ke, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSaudara, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNomor_Ijazah, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAsal_Sekolah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                            .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbKWn, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(tema1Layout.createSequentialGroup()
                                    .addComponent(txtNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNISN))
                                .addComponent(cbAgama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNama)
                                .addGroup(tema1Layout.createSequentialGroup()
                                    .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbLaki)
                                        .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbCewe)
                                        .addComponent(tglsiwa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tema1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNamaFileBuku)))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        tema1Layout.setVerticalGroup(
            tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tema1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tema1Layout.createSequentialGroup()
                        .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tema1Layout.createSequentialGroup()
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNISN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNamaFileBuku))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaSiswa)
                            .addGroup(tema1Layout.createSequentialGroup()
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTTL)
                                    .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTempat)
                                        .addComponent(tglsiwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbLaki)
                                .addComponent(rbCewe))
                            .addComponent(lblJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAgama)
                            .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKWn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKewarganegaraan))
                        .addGap(18, 18, 18)
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_anak_Ke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtSaudara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAsal_Sekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNomor_Ijazah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_Tahun_Angkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblALamat)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaSiswa1)
                    .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Siswa", tema1);

        clPanelTransparan2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Ayah"));

        lblNamaAyah1.setText("Nama Ayah");

        lblTempat1.setText("Tempat Lahir");

        lblTanggal1.setText("Tgl Lahir");

        lblAgamaAyah1.setText("Agama");

        lblPendidikanAyah1.setText("Pendidikan Terakhir");

        lblPekerjaan1.setText("Pekerjaan");

        lblPenghasilanAyah1.setText("Penghasilan perbulan");

        cbpenghasilanAyah1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "-", "<  250.000", "250.000 - 500.000", "500.000 - 1.000.000 ", "1.000.000 - 2.000.000 ", "2.000.000 - 3.000.000", "3.000.000 - 5.000.000", "> 5.000.000" }));

        cbAgamaAYah1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Islam", "Kristen Katholik", "Kristen Protestan", "Hindu", "Budha", "Konghucu", "Kepercayaan" }));

        tglAyah1.setDateFormatString("dd MMMM yyyy");

        cbPendidikanAyah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "SD", "SMP", "SMA", "D3", "S1", "S2", "S3" }));

        jLabel10.setText("Rp.");

        javax.swing.GroupLayout clPanelTransparan2Layout = new javax.swing.GroupLayout(clPanelTransparan2);
        clPanelTransparan2.setLayout(clPanelTransparan2Layout);
        clPanelTransparan2Layout.setHorizontalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPenghasilanAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTempat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgamaAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPendidikanAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPekerjaan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbpenghasilanAyah1, 0, 1, Short.MAX_VALUE)
                    .addComponent(txtpekerjaanAyah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPendidikanAyah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbAgamaAYah1, 0, 122, Short.MAX_VALUE)
                    .addComponent(tglAyah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNAmaAyah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttmpatAyah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(283, 283, 283))
        );
        clPanelTransparan2Layout.setVerticalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNAmaAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttmpatAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgamaAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAgamaAYah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPendidikanAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPendidikanAyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPekerjaan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpekerjaanAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPenghasilanAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbpenghasilanAyah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        cbPenghasilanIbu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "-", "<  250.000", "250.000 - 500.000", "500.000 - 1.000.000 ", "1.000.000 - 2.000.000 ", "2.000.000 - 3.000.000", "3.000.000 - 5.000.000", "> 5.000.000" }));

        label17.setText("Nama Ibu");

        label24.setText("Pendidikan Terakhir");

        label26.setText("Penghasilan perbulan");

        label25.setText("Pekerjaan");

        label18.setText("Tempat Lahir");

        tglIbu1.setDateFormatString("dd MMMM yyyy");

        CbAgamaIbu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Islam", "Kristen Katholik", "Kristen Protestan", "Hindu", "Budha", "Konghucu", "Kepercayaan" }));

        cbPendidikanIbu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D3", "S1", "S2", "S3" }));

        label20.setText("Agama");

        label19.setText("Tgl Lahir");

        javax.swing.GroupLayout clPanelTransparan3Layout = new javax.swing.GroupLayout(clPanelTransparan3);
        clPanelTransparan3.setLayout(clPanelTransparan3Layout);
        clPanelTransparan3Layout.setHorizontalGroup(
            clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPekerjaanIbu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPendidikanIbu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CbAgamaIbu1, 0, 126, Short.MAX_VALUE)
                    .addComponent(tglIbu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTempatIbu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNamaIbu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPenghasilanIbu1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        clPanelTransparan3Layout.setVerticalGroup(
            clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaIbu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempatIbu1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clPanelTransparan3Layout.createSequentialGroup()
                        .addComponent(tglIbu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbAgamaIbu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPendidikanIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPekerjaanIbu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPenghasilanIbu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tema2Layout = new javax.swing.GroupLayout(tema2);
        tema2.setLayout(tema2Layout);
        tema2Layout.setHorizontalGroup(
            tema2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clPanelTransparan2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clPanelTransparan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tema2Layout.setVerticalGroup(
            tema2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(tema2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clPanelTransparan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clPanelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Orang Tua", tema2);

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_anak_KeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anak_KeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anak_KeActionPerformed

    private void txtNISKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNISKeyTyped
        if (txtNIS.getText().length() == 9) {
            evt.consume();
        }

        //untuk set hanya angka saja
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNISKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         jfc=new JFileChooser();
        if(jfc.showOpenDialog(jLabelGambar)==JFileChooser.APPROVE_OPTION){
            
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(200, 250, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            
            jLabelGambar.setIcon(imageIcon);
            jLabelNamaFileBuku.setText(jfc.getSelectedFile().getName());
            
            file=new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txtNIS.getText().equals("")|| txtPekerjaanIbu1.getText().equals("")){
            input();
        cs.tambahsiswa();
        reset();
        try {
            String path=new File(".").getCanonicalPath();
            FileUtils.copyFileToDirectory(file, new File(path+"/image"));
        } catch (IOException ex) {
            Logger.getLogger(inputSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            input();
        cs.ubah();
     
        try {
            String path=new File(".").getCanonicalPath();
            FileUtils.copyFileToDirectory(file, new File(path+"/image"));
        } catch (IOException ex) {
            Logger.getLogger(inputSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
           reset();
           dispose();
              DataSiswa ds = new DataSiswa();
      ds.tampil();
        }

   
        
      
        /*
        Book book=new Book();
      //  book.setTitle(jTextFieldTitle.getText());
        book.setImage(jLabelNamaFileBuku.getText());
        bookService.save(book);
        bookTableModel.save(book);
        */
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
public void input(){
    cs.setNIS(Integer.parseInt(txtNIS.getText()));
        cs.setNISN(txtNISN.getText());
        cs.setNama_Lengkap(txtNama.getText());
        cs.setTempat_Lahir(txtTempat.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMMM yyyy", new Locale("id"));
        String tgl_lhir_siswa = String.valueOf(sdf.format(tglsiwa.getDate()));
        cs.setTanggal(tgl_lhir_siswa);
           if(rbLaki.isSelected()){
            cs.setJenis_Kelamin(rbLaki.getText());
        }else{
            if(rbCewe.isSelected()){
                cs.setJenis_Kelamin(rbCewe.getText());
            }
        }
        cs.setAgama_siswa(cbAgama.getSelectedItem().toString());
        cs.setKewarganegaraan(cbKWn.getSelectedItem().toString());
        cs.setAnakKe(txt_anak_Ke.getText());
        cs.setSaudara(txtSaudara.getText());
        cs.setAsalSekolah(txtAsal_Sekolah.getText());
        cs.setNomor_IJazah(txtNomor_Ijazah.getText());
        cs.setHp(txtHP.getText());
        cs.setAlamat(txtAlamat.getText());
        cs.setGambar(jLabelNamaFileBuku.getText());
        cs.setTahun_Ankatan(cb_Tahun_Angkatan.getSelectedItem().toString());
        cs.setNama_ayah(txtNAmaAyah1.getText());
        cs.setTempat_Lahir_ayah(txttmpatAyah1.getText());
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd MMMMM yyyy", new Locale("id"));
        String tgl_ayah = String.valueOf(sdf2.format(tglAyah1.getDate()));
        cs.setTanggal_Ayah(tgl_ayah);
        cs.setAgama_Ayah(cbAgamaAYah1.getSelectedItem().toString());
        cs.setPendidikan_ayah(cbPendidikanAyah.getSelectedItem().toString());
        cs.setPekrjaan_Ayah(txtpekerjaanAyah1.getText());
        cs.setPenghasilan_ayah(cbpenghasilanAyah1.getSelectedItem().toString());
        cs.setNama_Ibu(txtNamaIbu1.getText());
        cs.setTempat_Lahir_Ibu(txtTempatIbu1.getText());
        SimpleDateFormat sdf3 = new SimpleDateFormat("dd MMMMM yyyy", new Locale("id"));
        String tgl_Ibu = String.valueOf(sdf3.format(tglIbu1.getDate()));
        cs.setTanggal_Lahir(tgl_Ibu);
        cs.setAgama_Ibu(CbAgamaIbu1.getSelectedItem().toString());
        cs.setPendidikan_Ibu(cbPendidikanIbu.getSelectedItem().toString());
        cs.setPekerjaan_ibu(txtPekerjaanIbu1.getText());
        cs.setPengahsilan_ibu(cbPenghasilanIbu1.getSelectedItem().toString());
        cs.setNIS(Integer.parseInt(txtNIS.getText()));
        
}
private void setTanggalDefault() {
        try {
            Date date = new SimpleDateFormat("dd MM-yyyy").parse("01-01-1989");
            Date dates = new SimpleDateFormat("dd-MM-yyyy").parse("01-01-2003");
            Date datew = new SimpleDateFormat("dd-MM-yyyy").parse("17-08-2017");
            tglsiwa.setDate(datew);
            tglAyah1.setDate(date);
            tglIbu1.setDate(date);
            
           

        } catch (ParseException ex) {
            Logger.getLogger(inputSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
public void reset(){
    txtNIS.setText("");
    txtHP.setText("");
    txtNISN.setText("");
    txtNama.setText("");
    txtTempat.setText("");
    txt_anak_Ke.setText("");
    txtSaudara.setText("");
    txtAsal_Sekolah.setText("");
    txtNomor_Ijazah.setText("");
    txtAlamat.setText("");
    txtNAmaAyah1.setText("");
    txttmpatAyah1.setText("");
    txtpekerjaanAyah1.setText("");
    txtNamaIbu1.setText("");
    txtTempatIbu1.setText("");
    txtPekerjaanIbu1.setText("");
    cbAgama.setSelectedItem(0);
    cbKWn.setSelectedItem(0);
    CbAgamaIbu1.setSelectedItem(0);
    cbAgamaAYah1.setSelectedItem(0);
    cbPendidikanIbu.setSelectedItem(0);
    cbpenghasilanAyah1.setSelectedItem(0);
    cbPenghasilanIbu1.setSelectedItem(0);
   grupJekel.clearSelection();
    
    
    
}

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                inputSiswa dialog = new inputSiswa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CbAgamaIbu1;
    public javax.swing.JComboBox<String> cbAgama;
    public javax.swing.JComboBox<String> cbAgamaAYah1;
    public javax.swing.JComboBox<String> cbKWn;
    private javax.swing.JComboBox<String> cbPendidikanAyah;
    private javax.swing.JComboBox<String> cbPendidikanIbu;
    public javax.swing.JComboBox<String> cbPenghasilanIbu1;
    public javax.swing.JComboBox<String> cb_Tahun_Angkatan;
    public javax.swing.JComboBox<String> cbpenghasilanAyah1;
    private model.ClPanelTransparan clPanelTransparan1;
    private model.ClPanelTransparan clPanelTransparan2;
    private model.ClPanelTransparan clPanelTransparan3;
    private javax.swing.ButtonGroup grupJekel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelGambar;
    public javax.swing.JLabel jLabelNamaFileBuku;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private usu.widget.Label label17;
    private usu.widget.Label label18;
    private usu.widget.Label label19;
    private usu.widget.Label label20;
    private usu.widget.Label label24;
    private usu.widget.Label label25;
    private usu.widget.Label label26;
    private javax.swing.JLabel lblALamat;
    private javax.swing.JLabel lblAgama;
    private usu.widget.Label lblAgamaAyah1;
    private javax.swing.JLabel lblJenisKelamin;
    private javax.swing.JLabel lblKewarganegaraan;
    private usu.widget.Label lblNamaAyah1;
    private javax.swing.JLabel lblNamaSiswa;
    private javax.swing.JLabel lblNamaSiswa1;
    private usu.widget.Label lblPekerjaan1;
    private usu.widget.Label lblPendidikanAyah1;
    private usu.widget.Label lblPenghasilanAyah1;
    private javax.swing.JLabel lblTTL;
    private usu.widget.Label lblTanggal1;
    private usu.widget.Label lblTempat1;
    public javax.swing.JRadioButton rbCewe;
    public javax.swing.JRadioButton rbLaki;
    private Background.tema tema1;
    private Background.tema tema2;
    public com.toedter.calendar.JDateChooser tglAyah1;
    public com.toedter.calendar.JDateChooser tglIbu1;
    public com.toedter.calendar.JDateChooser tglsiwa;
    public javax.swing.JTextArea txtAlamat;
    public javax.swing.JTextField txtAsal_Sekolah;
    public javax.swing.JTextField txtHP;
    public usu.widget.TextBox txtNAmaAyah1;
    public javax.swing.JTextField txtNIS;
    public javax.swing.JTextField txtNISN;
    public javax.swing.JTextField txtNama;
    public usu.widget.TextBox txtNamaIbu1;
    public javax.swing.JTextField txtNomor_Ijazah;
    public usu.widget.TextBox txtPekerjaanIbu1;
    public javax.swing.JTextField txtSaudara;
    public javax.swing.JTextField txtTempat;
    public usu.widget.TextBox txtTempatIbu1;
    public javax.swing.JTextField txt_anak_Ke;
    public usu.widget.TextBox txtpekerjaanAyah1;
    public usu.widget.TextBox txttmpatAyah1;
    // End of variables declaration//GEN-END:variables
}
